package hu.laurel.sqlpulse.integration.postgres

import hu.laurel.sqlpulse.data.schema.GeneratedKind
import hu.laurel.sqlpulse.data.schema.RoutineKind
import hu.laurel.sqlpulse.data.schema.SchemaRepository
import hu.laurel.sqlpulse.data.schema.TableKind
import hu.laurel.sqlpulse.data.sql.CellValue
import hu.laurel.sqlpulse.data.sql.ColumnFilter
import hu.laurel.sqlpulse.data.sql.ColumnSort
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

/**
 * The schema browser against a real PostgreSQL: what SchemaRepository gets back through
 * [hu.laurel.sqlpulse.data.sql.dialect.PostgresCatalog], with nothing mocked but the Android half
 * of the session manager.
 */
class PostgresSchemaIntegrationTest {

    private lateinit var fixture: PostgresFixture
    private lateinit var schema: SchemaRepository

    @Before
    fun connect() {
        fixture = PostgresFixture()
        schema = SchemaRepository(fixture.manager)
        fixture.execute(
            """
            CREATE TABLE ${fixture.t("customers")} (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email varchar(120) NOT NULL UNIQUE,
                "Display Name" text COLLATE "C",
                balance numeric(10,2) NOT NULL DEFAULT 0,
                tags text[],
                created timestamptz NOT NULL DEFAULT now(),
                total_cents bigint GENERATED ALWAYS AS ((balance * 100)::bigint) STORED
            )
            """.trimIndent(),
            "COMMENT ON TABLE ${fixture.t("customers")} IS 'who buys'",
            "COMMENT ON COLUMN ${fixture.t("customers")}.email IS 'login'",
            """
            CREATE TABLE ${fixture.t("orders")} (
                id serial PRIMARY KEY,
                customer_id integer NOT NULL REFERENCES ${fixture.t("customers")} (id) ON DELETE CASCADE ON UPDATE RESTRICT,
                placed date NOT NULL,
                amount numeric(10,2) CHECK (amount >= 0)
            )
            """.trimIndent(),
            "CREATE INDEX orders_placed_idx ON ${fixture.t("orders")} (placed DESC, customer_id)",
            "CREATE INDEX orders_double_idx ON ${fixture.t("orders")} ((amount * 2)) WHERE amount > 0",
            // A composite key, to prove the two columns stay paired in order.
            """
            CREATE TABLE ${fixture.t("lines")} (
                order_id integer, line_no integer, sku text,
                PRIMARY KEY (order_id, line_no)
            )
            """.trimIndent(),
            "CREATE TABLE ${fixture.t("shipments")} (order_id integer, line_no integer, " +
                "FOREIGN KEY (order_id, line_no) REFERENCES ${fixture.t("lines")} (order_id, line_no) ON DELETE SET NULL)",
            "CREATE VIEW ${fixture.t("big_orders")} AS SELECT id, amount FROM ${fixture.t("orders")} WHERE amount > 100",
            "CREATE MATERIALIZED VIEW ${fixture.t("order_totals")} AS SELECT customer_id, sum(amount) AS total FROM ${fixture.t("orders")} GROUP BY 1",
            """
            CREATE TABLE ${fixture.t("events")} (at date NOT NULL, what text) PARTITION BY RANGE (at)
            """.trimIndent(),
            "CREATE TABLE ${fixture.t("events_2024")} PARTITION OF ${fixture.t("events")} FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')",
            "CREATE TABLE ${fixture.t("Mixed Case \"Table\"")} (\"Weird Col\" int PRIMARY KEY, other text)",
            """
            CREATE FUNCTION ${fixture.t("double_it")}(x integer) RETURNS integer LANGUAGE sql AS 'SELECT x * 2'
            """.trimIndent(),
            """
            CREATE FUNCTION ${fixture.t("double_it")}(x numeric) RETURNS numeric LANGUAGE sql AS 'SELECT x * 2'
            """.trimIndent(),
            "CREATE PROCEDURE ${fixture.t("noop")}() LANGUAGE sql AS ''",
            """
            CREATE FUNCTION ${fixture.t("touch")}() RETURNS trigger LANGUAGE plpgsql AS 'BEGIN RETURN NEW; END'
            """.trimIndent(),
            "CREATE TRIGGER touch_before BEFORE INSERT OR UPDATE ON ${fixture.t("orders")} FOR EACH ROW EXECUTE FUNCTION ${fixture.t("touch")}()",
            "INSERT INTO ${fixture.t("customers")} (email, \"Display Name\", balance) VALUES " +
                "('a@example.com', 'Ádám', 10.50), ('b@example.com', NULL, 0), ('c@example.com', 'Cecil', 99.99)",
            "INSERT INTO ${fixture.t("orders")} (customer_id, placed, amount) VALUES (1, '2024-03-01', 120), (1, '2024-04-01', 5), (2, '2024-05-01', NULL)",
        )
    }

    @After
    fun disconnect() {
        if (this::fixture.isInitialized) fixture.close()
    }

    @Test
    fun `tables, views and materialized views are listed with their kind, comment and size`() = runBlocking {
        val tables = schema.tables(fixture.schema).associateBy { it.name }
        assertEquals(TableKind.TABLE, tables.getValue("customers").kind)
        assertEquals("who buys", tables.getValue("customers").comment)
        assertEquals(TableKind.VIEW, tables.getValue("big_orders").kind)
        assertEquals(TableKind.VIEW, tables.getValue("order_totals").kind)
        assertEquals(TableKind.TABLE, tables.getValue("events").kind)
        assertEquals(TableKind.TABLE, tables.getValue("Mixed Case \"Table\"").kind)
        assertNotNull(tables.getValue("customers").dataBytes)
        assertTrue(tables.getValue("customers").indexBytes!! > 0)
        // A view has no storage of its own.
        assertNull(tables.getValue("big_orders").dataBytes)
        // Nothing has been analyzed yet, so there is no estimate rather than a wrong one.
        assertNull(tables.getValue("orders").approximateRows)
        fixture.execute("ANALYZE ${fixture.t("orders")}")
        assertEquals(3L, schema.tables(fixture.schema, refresh = true).first { it.name == "orders" }.approximateRows)
        assertEquals(tables.keys.sorted(), tables.keys.toList())
    }

    @Test
    fun `columns carry type, default, key, identity, generation, collation and comment`() = runBlocking {
        val columns = schema.structure(fixture.schema, "customers").columns.associateBy { it.name }
        assertEquals(listOf("id", "email", "Display Name", "balance", "tags", "created", "total_cents"), columns.keys.toList())

        with(columns.getValue("id")) {
            assertEquals("integer", typeName)
            assertTrue(isPrimaryKey)
            assertFalse(nullable)
            assertTrue(extra!!.contains("auto_increment"))
        }
        with(columns.getValue("email")) {
            assertEquals("character varying(120)", typeName)
            assertEquals("login", comment)
            assertFalse(isPrimaryKey)
        }
        assertEquals("C", columns.getValue("Display Name").collation)
        assertTrue(columns.getValue("Display Name").nullable)
        assertEquals("numeric(10,2)", columns.getValue("balance").typeName)
        assertEquals("0", columns.getValue("balance").defaultValue)
        assertEquals("text[]", columns.getValue("tags").typeName)
        assertEquals("timestamp with time zone", columns.getValue("created").typeName)
        assertEquals("now()", columns.getValue("created").defaultValue)
        with(columns.getValue("total_cents")) {
            assertEquals(GeneratedKind.STORED, generatedKind)
            assertNull(defaultValue)
            assertTrue(generationExpression!!.contains("balance"))
        }
        // serial: the nextval default is what makes the server fill it in.
        val orders = schema.structure(fixture.schema, "orders").columns.associateBy { it.name }
        assertTrue(orders.getValue("id").defaultValue!!.startsWith("nextval("))
        assertEquals("auto_increment", orders.getValue("id").extra)
    }

    @Test
    fun `indexes list their key columns in order, expressions included`() = runBlocking {
        val indexes = schema.structure(fixture.schema, "orders").indexes.associateBy { it.name }
        assertEquals(listOf("id"), indexes.getValue("orders_pkey").columns)
        assertTrue(indexes.getValue("orders_pkey").unique)
        assertEquals(listOf("placed", "customer_id"), indexes.getValue("orders_placed_idx").columns)
        assertFalse(indexes.getValue("orders_placed_idx").unique)
        // The server's own text for the expression, which spells out the cast it chose.
        assertTrue(indexes.getValue("orders_double_idx").columns.single().startsWith("(amount * 2"))
        val customers = schema.structure(fixture.schema, "customers").indexes
        assertTrue(customers.any { it.unique && it.columns == listOf("email") })
    }

    @Test
    fun `foreign keys come with their rules, composite ones keep their column pairs`() = runBlocking {
        val orderKey = schema.structure(fixture.schema, "orders").foreignKeys.single()
        assertEquals("customer_id", orderKey.column)
        assertEquals(fixture.schema, orderKey.referencedDatabase)
        assertEquals("customers", orderKey.referencedTable)
        assertEquals("id", orderKey.referencedColumn)
        assertEquals("CASCADE", orderKey.onDelete)
        assertEquals("RESTRICT", orderKey.onUpdate)
        // RESTRICT is what a key does when nothing was declared, so only the CASCADE is worth a line.
        assertEquals("ON DELETE CASCADE", orderKey.ruleSummary)

        val composite = schema.structure(fixture.schema, "shipments").foreignKeys
        assertEquals(listOf("order_id" to "order_id", "line_no" to "line_no"), composite.map { it.column to it.referencedColumn })
        assertEquals("SET NULL", composite.first().onDelete)
    }

    @Test
    fun `the map and the row walk read the same keys from both ends`() = runBlocking {
        val edges = schema.links(fixture.schema).associateBy { it.from }
        assertEquals("customers", edges.getValue("orders").to)
        assertEquals(listOf("customer_id"), edges.getValue("orders").columns)
        assertEquals(listOf("order_id", "line_no"), edges.getValue("shipments").columns)

        val children = fixture.use { hu.laurel.sqlpulse.data.sql.dialect.PostgresDialect.catalog.referencingKeys(it, fixture.schema, "customers") }
        assertEquals(1, children.size)
        assertEquals("orders", children.single().childTable)
        assertEquals("customer_id", children.single().childColumn)

        val names = schema.columnNames(fixture.schema).associateBy { it.table }
        assertEquals(listOf("order_id", "line_no"), names.getValue("lines").primaryKey)
        assertEquals(listOf("id"), names.getValue("customers").primaryKey)
        assertTrue("big_orders" in names)
    }

    @Test
    fun `check constraints and partitions are read`() = runBlocking {
        val checks = schema.structure(fixture.schema, "orders").checks
        assertEquals(1, checks.size)
        assertTrue(checks.single().expression!!.startsWith("amount >= 0"))

        val events = schema.structure(fixture.schema, "events")
        assertTrue(events.partitioned)
        assertEquals("events_2024", events.partitions.single().name)
        assertEquals("RANGE", events.partitions.single().method)
        assertTrue(events.partitions.single().expression!!.contains("2024-01-01"))
        assertFalse(schema.structure(fixture.schema, "orders").partitioned)
    }

    @Test
    fun `the DDL tab shows the table as it could be created, and a view as its query`() = runBlocking {
        val ddl = schema.ddl(fixture.schema, "customers")
        assertTrue(ddl, ddl.startsWith("CREATE TABLE \"${fixture.schema}\".\"customers\" ("))
        assertTrue(ddl, ddl.contains("\"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL"))
        assertTrue(ddl, ddl.contains("\"Display Name\" text COLLATE \"C\""))
        assertTrue(ddl, ddl.contains("\"balance\" numeric(10,2) DEFAULT 0 NOT NULL"))
        assertTrue(ddl, ddl.contains("GENERATED ALWAYS AS ("))
        assertTrue(ddl, ddl.contains("PRIMARY KEY (id)"))
        assertTrue(ddl, ddl.contains("UNIQUE (email)"))

        val orders = schema.ddl(fixture.schema, "orders")
        assertTrue(orders, orders.contains("FOREIGN KEY (customer_id) REFERENCES"))
        assertTrue(orders, orders.contains("CREATE INDEX orders_placed_idx"))
        // The primary key's index is the constraint's, not a second statement.
        assertFalse(orders, orders.contains("CREATE UNIQUE INDEX orders_pkey"))

        assertTrue(schema.ddl(fixture.schema, "big_orders").startsWith("CREATE VIEW"))
        assertTrue(schema.ddl(fixture.schema, "order_totals").startsWith("CREATE MATERIALIZED VIEW"))
        assertEquals("", schema.ddl(fixture.schema, "nothing_like_this"))
    }

    @Test
    fun `the DDL tab's statements run as shown`() = runBlocking {
        val ddl = schema.ddl(fixture.schema, "orders").replace("\"${fixture.schema}\".\"orders\"", "\"${fixture.schema}\".\"orders_copy\"")
            .replace("orders_pkey", "copy_pkey").replace("orders_placed_idx", "copy_placed_idx").replace("orders_double_idx", "copy_double_idx")
        fixture.use { connection ->
            ddl.split(";\n\n").map { it.trim().trimEnd(';') }.filter { it.isNotEmpty() }.forEach { connection.createStatement().use { s -> s.execute(it) } }
        }
        assertEquals("0", fixture.scalar("SELECT count(*) FROM ${fixture.t("orders_copy")}"))
    }

    @Test
    fun `routines are listed by signature and their source is available`() = runBlocking {
        val routines = schema.routines(fixture.schema)
        val signatures = routines.map { it.name }
        assertTrue(signatures.toString(), "double_it(x integer)" in signatures && "double_it(x numeric)" in signatures)
        assertEquals(RoutineKind.PROCEDURE, routines.first { it.name == "noop()" }.kind)
        assertEquals("integer", routines.first { it.name == "double_it(x integer)" }.returns)
        val source = schema.routineDdl(fixture.schema, routines.first { it.name == "double_it(x numeric)" })
        assertTrue(source, source.contains("numeric") && source.contains("x * 2"))
    }

    @Test
    fun `triggers say when they fire and on what`() = runBlocking {
        val trigger = schema.triggers(fixture.schema).single()
        assertEquals("touch_before", trigger.name)
        assertEquals("orders", trigger.table)
        assertEquals("BEFORE", trigger.timing)
        assertEquals("INSERT OR UPDATE", trigger.event)
    }

    @Test
    fun `a table is paged, sorted, filtered and counted by its quoted name`() = runBlocking {
        val page = schema.preview(fixture.schema, "customers", limit = 2, offset = 1, sort = ColumnSort("id", descending = false))
        assertEquals(2, page.rowCount)
        assertEquals(CellValue.Text("b@example.com"), page.rows[0][page.columns.indexOfFirst { it.label == "email" }])
        assertEquals(3L, schema.rowCount(fixture.schema, "customers"))

        // A name with a quote, a space and capitals, and a column named the same way.
        fixture.execute("INSERT INTO ${fixture.t("Mixed Case \"Table\"")} VALUES (1, 'x'), (2, 'y')")
        assertEquals(2L, schema.rowCount(fixture.schema, "Mixed Case \"Table\""))
        val sorted = schema.preview(fixture.schema, "Mixed Case \"Table\"", sort = ColumnSort("Weird Col", descending = true))
        assertEquals(CellValue.Number("2"), sorted.rows.first().first())
    }

    @Test
    fun `the first bytes of a bytea column are read without fetching the rest`() = runBlocking {
        fixture.execute(
            "CREATE TABLE ${fixture.t("blobs")} (id int PRIMARY KEY, payload bytea)",
            "INSERT INTO ${fixture.t("blobs")} VALUES (1, decode(repeat('ab', 100), 'hex'))",
        )
        val (head, more) = schema.blobBytes(fixture.schema, "blobs", mapOf("id" to "1"), "payload", maxBytes = 16)
        assertEquals(16, head.size)
        assertEquals(0xab.toByte(), head[0])
        assertTrue(more)
    }

    @Test
    fun `an unreadable schema name or table gives an empty structure, not a crash`() = runBlocking {
        assertTrue(schema.structure(fixture.schema, "nothing_like_this").columns.isEmpty())
        assertTrue(schema.tables("no_such_schema_${System.nanoTime()}").isEmpty())
    }
}
